language: node_js
node_js: stable
before_install:
- export TZ='Asia/Shanghai'
install:
- npm install -g gitbook
- npm install -g gitbook-cli
- gitbook install
script:
- gitbook build
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github-token: 
    secure: IZhjAzqBQTVWQK//MpWuyuMyb9KRLInpxajweL3mWURskD/d278lQ5CxgSQDCNvu31DEgiNLhMr8jEySg5VLGKaQBIVO3/myIaXYfnZ1IvxmkkGUlebtUd9hb9xrxNmmNe9oC2QE00R99JHTGZDm5fE8hRdzyCfCbaCGMFjLT6CwzjqTUUa38/00UPqy7gG6d7pywXY4Xd4a+2moI1HMjVOTlrzcMFYOTZxd41pT6xpG16XHCRK3ZDsX0/nrCQcFRgpSzKekvv3ez6EpVbbi2kFYG4HIMpoAMsN8tCu6arQy2cs+ICj8KxlAgC5acXBpASU20sO0eoh89ZL9PWB/JOrEYxNKJKoI2QFLfwXK0PjDMsYxRWVRYNmeik/NoMm5XS9JganRfwzw+IrqFBHwKr/pA1OQdXgxM21DwPPpSVXRRxEvy5BdtJjeoYQ+Lv6/puAHs/fcRGW8uBL0Vct9C0hxOPJ2gKujY7NX8lrNPuawr39tohYLjt19Lp+k8EdCF/LPGZdUJ0BjcKB4/68H2bJkOtI0S25fimzqPmEknfl84z1hAKO3ni/I2+iDaAAEYMSic9tsrQyr9hTKI+gtx9TSHwl0NJX9wTwcY38b6CyaeGlHUrOMP+8ezyolnlREptWH9QpRoxZrz5en3LP1ocJ2xl1EjR9oYJwD+JTkGgU=
  local_dir: _book
  fqdn: tonydeng.github.io
  name: Travis CI
  email: travis@travis-ci.org
  on:
    branch: master