language: node_js
node_js: stable
before_install:
- export TZ='Asia/Shanghai'
install:
- npm install -g gitbook
- npm install -g gitbook-cli
- gitbook install
script:
- gitbook build
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  # github-token:
  #   secure: Vqmj93yEQiHf4tffg20z7Sfhu4HfTumkSmf4W7szIk4AmB9edmoCtWasmnJ2OTVpHlL1k6uFVNTwFVjK7dSVv97DGCcdyyoZL50Ag+yEhj3zwkAJY8Bt0CAHVGdYdHXUoP4kV1OHfPo4T8gG7QaHtuhtfyOQZITGqW/Hg6bfhpVd65NsNoG+m5mE19cZumRyP6drwiG+mfF4Go4z5qF7UZ5S10rWkDeH8npLEEDmpeseP1EQecKuUJsqjWZnR0dTljFTNPAXbMhiBB2tngpfKnVjcKDPm3GACdO8ViWwBV8mK20eioIrFW0m1gcg+eds0iGEIrgF7o59aj2MNCTXVif4N3NxRXMeFkrATqf9dAdxnfYC9ctSLF2+OuD/KhAY7HL5tGphvDpmYNbs2uEEV7ULNaLKlNijbOyLZiS7fFvGAQgy/md82MHYRIIhPHK5iX09f7iKDW37frEJeBWv/2al9Cv7THiKMyIGv8I3iZPkDk0ATxijghAlfR2rXO+dIK3Gjk85ZIenIjvRWgbhEdHG/r/ZsoqneqVMqPpK3oPVNa/jjT6dsAZURB+UVDlo4tfigKUOpdz1mUe6FMyCevRpc29ahOKuGTWo2XJLdKniT611otdfHjBwQjf+E6qH2+YlyUDsG7c2NjDpFOJrXrM057mzWh0Cl8OlxI8CyDQ=
  local_dir: _book
  fqdn: tonydeng.github.io
  name: Travis CI
  email: travis@travis-ci.org
  on:
    branch: master
env:
  global:
    GH_REF: github.com/tonydeng/architect-manual.git
    secure: bqJPF4/2lYi+r9W+EHfQh9zCvvBiWipZZrAD36HzUAs0PTUTS8UwgtUJKDjQaClQh+6mRQlaPe995kzQ/cMt6V+YKF0TrK/0tYmd8f0hfFvw1KL2QUX12SJQtz6fbG6ODF47hGdYwteeOnKM64Wq/2nIefyfX5jh8UGcFFlgDEG3vt+TyZIYL9Kj4Rmp1PYIG5a7TBkPsI9eQPrsxp0taiA+/6i77rMMIP/R8b23L8A6fN0BPrziDQROfu4miSRBetymS20f5kUwx6yHSvKfHbmlBqtmIPJZkTo2+FEF53815dHG6DfKTwcAyUThnbfO16FsI3luikGtkz4BfYmCNtfW3rkrJo7uOpoQEjJXpiBITad8QviYyhQ2Sx89IpXeFd5U3RlACyqripxmVXePzWHuMEqi/TkfzQPsQgMuvh3o6zjP1CpOR9Qwya5dKcl4o3KgXWV2JjjLM8yjjQ5Jl2yn5Cn0NDImRIGJT/Lq8NfYWEmsG/Dj1WzQZnfhbQn7qIKj/yrM1ev6fbddoJgQDYswpREeA88AQiEQMd4meLUEm5ZO7pWlgiskcIixCldPMkXfzBSK/hCrP+WE40UKuslVFgLvqpB7PoRbeVmN+0x/P16zSTKbEfM2JoGuHrAqldmrnT7oWrp5Uu8Ll/P/+ijmiz6CqcuwNruvjnNkA3w=
