language: node_js
node_js: stable
before_install:
- export TZ='Asia/Shanghai'
install:
- npm install -g gitbook
- npm install -g gitbook-cli
- gitbook install
script:
- gitbook build
branches:
  only:
  - master
deploy:
  provider: pages
  skip_cleanup: true
  github-token:
    secure: aK4jPQFX4Xl9dCn7XQ7NAYZGYywSPPXzn54z4sN0Cd71rbs8L/M0MWkl3oi6qKbwOTCnlrHZzyLscug9pILMRoLmQFUDZgSjmz7ocwKJJxMd/WWgQKEzODTx0/ut5Laiyuu3+sOw83xaMoSEspwNOME+bUngXazFOnW3cKPy3/65zGebv6Aff0dVLPUuLdFWyXtnbAbLHlSXXVr8XacNgqmhQeVdbwjzbdQDg2QLEkQfPMnOI7/jEQ83jcIRxYJTCy55jQTEOWyzGsfqv2bmpqxSAKmbTbD+ffHE0Wdat1ifK8xqhjKGoLVpwVCOuk5DZm5R5T7GKsT1DZs9s2eu2076hPhHwpwcugAFU879gAPZBSe6ZWb8N6tc/CbecO8gYFhuqBve9O06wjldm489VPAZjP291313uY0S7m3n1pbrj2A/XN4CR9oCEfBkQup5XnMqLWOvYpqfVcObkwIUpFhr0zRzDspGBZTPVr9PSqoKQ4Rn3GfoHjkIgjPHf3krNLqrO03RVLouP3rO4hvK5LQpAp3259FSgcX9sU0hPWhpSmAxMZ7VG+bMvSfknzcgqGxDPI5isriIzQVfI1NcBcYccUbX8CWbugkIgGVELKsY6XUqpjp8cRZUpmaULqX1SlMMQg4stght5fW0y3XZjbXyOepnrRPcSEkYv+oibnA=
  local_dir: _book
  fqdn: tonydeng.github.io
  name: Travis CI
  email: travis@travis-ci.org
  on:
    branch: master
